const TagInfo = {
  algorithm: { category: "COMPUTER SCIENCE", label: "Algorithm" },
  network: { category: "COMPUTER SCIENCE", label: "Network" },
  css: { category: "CSS", label: "CSS" },
  scss: { category: "CSS", label: "SCSS" },
  emotion: { category: "CSS", label: "Emotion" },
  style_components: { category: "CSS", label: "Styled-Components" },
  gatsby: { category: "FRAMEWORK", label: "Gatsby" },
  nextjs: { category: "FRAMEWORK", label: "Next.js" },
  intellij: { category: "IDE", label: "IntelliJ" },
  javascript: {
    category: "LANGUAGE",
    label: "JavaScript",
  },
  typescript: { category: "LANGUAGE", label: "TypeScript" },
  python3: { category: "LANGUAGE", label: "Python3" },
  react: { category: "LIBRARY", label: "React" },
  redux_persist: { category: "LIBRARY", label: "Redux-Persist" },
  redux: { category: "LIBRARY", label: "Redux" },
  recoil: { category: "LIBRARY", label: "Recoil" },
  axios: { category: "LIBRARY", label: "Axios" },
  lodash: { category: "LIBRARY", label: "Lodash" },
  git: { category: "MANAGEMENT", label: "Git" },
  git_hub: { category: "MANAGEMENT", label: "GitHub" },
  npm: { category: "PACKAGE MANAGER", label: "npm" },
  yarn: { category: "PACKAGE MANAGER", label: "yarn" },
  yarn_berry: { category: "PACKAGE MANAGER", label: "yarn berry" },
  jest: { category: "TEST", label: "Jest" },
};
export default TagInfo;
