import { categoryType } from "@src/models";

const TagInfo: {
  [key: string]: {
    category: categoryType;
    label: string;
    color?: string;
    bg?: string;
    bg_hover?: string;
    text?: string;
    text_hover?: string;
    border?: string;
  };
} = {
  algorithm: { category: "COMPUTER SCIENCE", label: "Algorithm" },
  programming: { category: "COMPUTER SCIENCE", label: "Programming" },
  network: { category: "COMPUTER SCIENCE", label: "Network" },
  css: {
    category: "CSS",
    label: "CSS",
    color: "#1572b6",
    bg: "bg-[#1572b6]",
    bg_hover: "hover:bg-[#1572b6]",
    text: "text-[#1572b6]",
    text_hover: "hover:text-[#1572b6]",
    border: "border-[#1572b6]",
  },
  scss: {
    category: "CSS",
    label: "SCSS",
    color: "#bf4080",
    bg: "bg-[#bf4080]",
    bg_hover: "hover:bg-[#bf4080]",
    text: "text-[#bf4080]",
    text_hover: "hover:text-[#bf4080]",
    border: "border-[#bf4080]",
  },
  emotion: {
    category: "CSS",
    label: "Emotion",
    color: "#d26ac2",
    bg: "bg-[#d26ac2]",
    bg_hover: "hover:bg-[#d26ac2]",
    text: "text-[#d26ac2]",
    text_hover: "hover:text-[#d26ac2]",
    border: "border-[#d26ac2]",
  },
  styled_components: {
    category: "CSS",
    label: "Styled-Components",
    color: "#ffa4e8",
    bg: "bg-[#ffa4e8]",
    bg_hover: "hover:bg-[#ffa4e8]",
    text: "text-[#ffa4e8]",
    text_hover: "hover:text-[#ffa4e8]",
    border: "border-[#ffa4e8]",
  },
  gatsby: {
    category: "FRAMEWORK",
    label: "Gatsby",
    color: "#663399",
    bg: "bg-[#663399]",
    bg_hover: "hover:bg-[#663399]",
    text: "text-[#663399]",
    text_hover: "hover:text-[#663399]",
    border: "border-[#663399]",
  },
  nextjs: { category: "FRAMEWORK", label: "Next.js" },
  intellij: { category: "IDE", label: "IntelliJ" },
  javascript: {
    category: "LANGUAGE",
    label: "JavaScript",
    color: "#fac905",
    bg: "bg-[#fac905]",
    bg_hover: "hover:bg-[#fac905]",
    text: "text-[#fac905]",
    text_hover: "hover:text-[#fac905]",
    border: "border-[#fac905]",
  },
  typescript: {
    category: "LANGUAGE",
    label: "TypeScript",
    color: "#3178c6",
    bg: "bg-[#3178c6]",
    bg_hover: "hover:bg-[#3178c6]",
    text: "text-[#3178c6]",
    text_hover: "hover:text-[#3178c6]",
    border: "border-[#3178c6]",
  },
  python3: { category: "LANGUAGE", label: "Python3" },
  html: {
    category: "LANGUAGE",
    label: "HTML",
    color: "#e44f26",
    bg: "bg-[#e44f26]",
    bg_hover: "hover:bg-[#e44f26]",
    text: "text-[#e44f26]",
    text_hover: "hover:text-[#e44f26]",
    border: "border-[#e44f26]",
  },
  react: {
    category: "LIBRARY",
    label: "React",
    color: "#61dbfb",
    bg: "bg-[#61dbfb]",
    bg_hover: "hover:bg-[#61dbfb]",
    text: "text-[#61dbfb]",
    text_hover: "hover:text-[#61dbfb]",
    border: "border-[#61dbfb]",
  },
  redux_persist: { category: "LIBRARY", label: "Redux-Persist" },
  redux: {
    category: "LIBRARY",
    label: "Redux",
    color: "#764abc",
    bg: "bg-[#764abc]",
    bg_hover: "hover:bg-[#764abc]",
    text: "text-[#764abc",
    text_hover: "hover:text-[#764abc]",
    border: "border-[#764abc]",
  },
  recoil: { category: "LIBRARY", label: "Recoil" },
  axios: { category: "LIBRARY", label: "Axios" },
  lodash: { category: "LIBRARY", label: "Lodash" },
  git: {
    category: "MANAGEMENT",
    label: "Git",
    color: "#000000",
    bg: "bg-black",
    bg_hover: "hover:bg-black",
    text: "text-black",
    text_hover: "hover:text-black",
    border: "border-black",
  },
  git_hub: {
    category: "MANAGEMENT",
    label: "GitHub",
    color: "#000000",
    bg: "bg-black",
    bg_hover: "hover:bg-black",
    text: "text-black",
    text_hover: "hover:text-black",
    border: "border-black",
  },
  npm: { category: "PACKAGE MANAGER", label: "npm" },
  yarn: { category: "PACKAGE MANAGER", label: "yarn" },
  yarn_berry: { category: "PACKAGE MANAGER", label: "yarn berry" },
  jest: {
    category: "TEST",
    label: "Jest",
    color: "#99425b",
    bg: "bg-[#99425b]",
    bg_hover: "hover:bg-[#99425b]",
    text: "text-[#99425b]",
    text_hover: "hover:text-[#99425b]",
    border: "border-[#99425b]",
  },
};
export default TagInfo;
