const TagsTable = {
  published: {
    all: [
      "yarn-berry-start",
      "yarn-berry-pnp",
      "vite-ts-react-path",
      "vite-react-ts-emotion-props-config",
      "vite-library-typescript",
      "utterances-to-giscus",
      "sync-async",
      "styled-components-global-style",
      "socket",
      "semantic-release",
      "reg-exp",
      "redux-RTK-with-ts",
      "redux-persist",
      "react-class-render",
      "python-rjust-ljust-zfill",
      "project-simple-kanban-board",
      "nextjs-large-page-data-warning",
      "nextjs-intl",
      "nextjs-image-blur",
      "nextjs-gtag",
      "network-note-01",
      "network-application-02",
      "mvc-pattern",
      "lodash",
      "javascript-intersection-observer-API",
      "javascript-forEach-map",
      "javascript-concat-push",
      "husky-precommit-unauthorized",
      "husky-git-hook",
      "husky-commlint",
      "http",
      "github-repo-union",
      "github-page-publish",
      "git-commit-template",
      "gatsby-add-table-of-contents-in-gatsby",
      "error-ts2802",
      "error-emeedauth",
      "cookie-session",
      "browser-rendering",
      "blog-version-2",
      "blog-auto-deploy",
      "axios-interceptor",
      "axios-config",
      "assignInlineVars-to-client-from-server",
    ],
    yarn: ["yarn-berry-start", "yarn-berry-pnp"],
    npm: ["yarn-berry-pnp", "vite-library-typescript", "error-emeedauth"],
    yarn_berry: ["yarn-berry-pnp"],
    vite: [
      "vite-ts-react-path",
      "vite-react-ts-emotion-props-config",
      "vite-library-typescript",
    ],
    typescript: [
      "vite-ts-react-path",
      "vite-react-ts-emotion-props-config",
      "vite-library-typescript",
      "utterances-to-giscus",
      "styled-components-global-style",
      "redux-RTK-with-ts",
      "project-simple-kanban-board",
      "nextjs-gtag",
      "lodash",
      "gatsby-add-table-of-contents-in-gatsby",
      "error-ts2802",
      "axios-interceptor",
      "axios-config",
    ],
    react: [
      "vite-ts-react-path",
      "vite-react-ts-emotion-props-config",
      "vite-library-typescript",
      "styled-components-global-style",
      "redux-RTK-with-ts",
      "react-class-render",
      "project-simple-kanban-board",
      "lodash",
      "github-page-publish",
      "gatsby-add-table-of-contents-in-gatsby",
      "axios-interceptor",
      "axios-config",
    ],
    javascript: [
      "vite-ts-react-path",
      "reg-exp",
      "redux-persist",
      "react-class-render",
      "lodash",
      "javascript-intersection-observer-API",
      "javascript-forEach-map",
      "javascript-concat-push",
      "github-page-publish",
      "axios-interceptor",
      "axios-config",
    ],
    emotion: [
      "vite-react-ts-emotion-props-config",
      "gatsby-add-table-of-contents-in-gatsby",
    ],
    nextjs: [
      "utterances-to-giscus",
      "nextjs-large-page-data-warning",
      "nextjs-intl",
      "nextjs-image-blur",
      "nextjs-gtag",
      "blog-version-2",
      "blog-auto-deploy",
      "assignInlineVars-to-client-from-server",
    ],
    giscus: ["utterances-to-giscus"],
    utterances: ["utterances-to-giscus"],
    network: [
      "sync-async",
      "socket",
      "network-note-01",
      "network-application-02",
      "http",
      "cookie-session",
      "browser-rendering",
    ],
    computer_science: [
      "sync-async",
      "network-note-01",
      "network-application-02",
      "mvc-pattern",
    ],
    styled_components: [
      "styled-components-global-style",
      "project-simple-kanban-board",
    ],
    css: ["styled-components-global-style", "browser-rendering"],
    semamtic_release: ["semantic-release"],
    github_actions: ["semantic-release", "blog-auto-deploy"],
    reg_exp: ["reg-exp"],
    redux: ["redux-RTK-with-ts", "redux-persist"],
    redux_persist: ["redux-persist"],
    python3: ["python-rjust-ljust-zfill"],
    react_beautiful_dnd: ["project-simple-kanban-board"],
    react_hook_form: ["project-simple-kanban-board"],
    recoil: ["project-simple-kanban-board"],
    next_intl: ["nextjs-intl"],
    plaiceholder: ["nextjs-image-blur"],
    gtag: ["nextjs-gtag"],
    google_analytics: ["nextjs-gtag"],
    lodash: ["lodash"],
    husky: ["husky-precommit-unauthorized", "husky-git-hook", "husky-commlint"],
    git: [
      "husky-git-hook",
      "husky-commlint",
      "github-repo-union",
      "git-commit-template",
      "error-emeedauth",
    ],
    commitlint: ["husky-commlint"],
    githubpage: ["github-page-publish"],
    intellij: ["git-commit-template"],
    gatsby: ["gatsby-add-table-of-contents-in-gatsby"],
    framer_motion: ["blog-version-2"],
    tailwind: ["blog-version-2"],
    "github_pages_deploy_action@v4": ["blog-auto-deploy"],
    axios: ["axios-interceptor", "axios-config"],
    vanilla_extract: ["assignInlineVars-to-client-from-server"],
  },
  unpublished: {
    all: [
      "yarn-berry-start",
      "yarn-berry-pnp",
      "vite-ts-react-path",
      "vite-react-ts-emotion-props-config",
      "vite-library-typescript",
      "utterances-to-giscus",
      "sync-async",
      "styled-components-global-style",
      "socket",
      "semantic-release",
      "reg-exp",
      "redux-RTK-with-ts",
      "redux-persist",
      "react-hook",
      "react-hook-state",
      "react-class-render",
      "python-rjust-ljust-zfill",
      "project-simple-kanban-board",
      "project-real-time-coin-info",
      "nextjs-large-page-data-warning",
      "nextjs-intl",
      "nextjs-image-blur",
      "nextjs-gtag",
      "network-note-01",
      "network-application-02",
      "mvc-pattern",
      "lodash",
      "javascript-intersection-observer-API",
      "javascript-forEach-map",
      "javascript-concat-push",
      "husky-precommit-unauthorized",
      "husky-git-hook",
      "husky-commlint",
      "http",
      "github-repo-union",
      "github-page-publish",
      "git-commit-template",
      "gatsby-add-table-of-contents-in-gatsby",
      "error-ts2802",
      "error-emeedauth",
      "cookie-session",
      "browser-rendering",
      "blog-version-2",
      "blog-auto-deploy",
      "axios-interceptor",
      "axios-config",
      "assignInlineVars-to-client-from-server",
    ],
    yarn: ["yarn-berry-start", "yarn-berry-pnp"],
    npm: ["yarn-berry-pnp", "vite-library-typescript", "error-emeedauth"],
    yarn_berry: ["yarn-berry-pnp"],
    vite: [
      "vite-ts-react-path",
      "vite-react-ts-emotion-props-config",
      "vite-library-typescript",
    ],
    typescript: [
      "vite-ts-react-path",
      "vite-react-ts-emotion-props-config",
      "vite-library-typescript",
      "utterances-to-giscus",
      "styled-components-global-style",
      "redux-RTK-with-ts",
      "project-simple-kanban-board",
      "project-real-time-coin-info",
      "nextjs-gtag",
      "lodash",
      "gatsby-add-table-of-contents-in-gatsby",
      "error-ts2802",
      "axios-interceptor",
      "axios-config",
    ],
    react: [
      "vite-ts-react-path",
      "vite-react-ts-emotion-props-config",
      "vite-library-typescript",
      "styled-components-global-style",
      "redux-RTK-with-ts",
      "react-hook",
      "react-hook-state",
      "react-class-render",
      "project-simple-kanban-board",
      "project-real-time-coin-info",
      "lodash",
      "github-page-publish",
      "gatsby-add-table-of-contents-in-gatsby",
      "axios-interceptor",
      "axios-config",
    ],
    javascript: [
      "vite-ts-react-path",
      "reg-exp",
      "redux-persist",
      "react-class-render",
      "lodash",
      "javascript-intersection-observer-API",
      "javascript-forEach-map",
      "javascript-concat-push",
      "github-page-publish",
      "axios-interceptor",
      "axios-config",
    ],
    emotion: [
      "vite-react-ts-emotion-props-config",
      "gatsby-add-table-of-contents-in-gatsby",
    ],
    nextjs: [
      "utterances-to-giscus",
      "nextjs-large-page-data-warning",
      "nextjs-intl",
      "nextjs-image-blur",
      "nextjs-gtag",
      "blog-version-2",
      "blog-auto-deploy",
      "assignInlineVars-to-client-from-server",
    ],
    giscus: ["utterances-to-giscus"],
    utterances: ["utterances-to-giscus"],
    network: [
      "sync-async",
      "socket",
      "network-note-01",
      "network-application-02",
      "http",
      "cookie-session",
      "browser-rendering",
    ],
    computer_science: [
      "sync-async",
      "network-note-01",
      "network-application-02",
      "mvc-pattern",
    ],
    styled_components: [
      "styled-components-global-style",
      "project-simple-kanban-board",
      "project-real-time-coin-info",
    ],
    css: ["styled-components-global-style", "browser-rendering"],
    semamtic_release: ["semantic-release"],
    github_actions: ["semantic-release", "blog-auto-deploy"],
    reg_exp: ["reg-exp"],
    redux: ["redux-RTK-with-ts", "redux-persist"],
    redux_persist: ["redux-persist"],
    python3: ["python-rjust-ljust-zfill"],
    react_beautiful_dnd: ["project-simple-kanban-board"],
    react_hook_form: ["project-simple-kanban-board"],
    recoil: ["project-simple-kanban-board", "project-real-time-coin-info"],
    react_helmet: ["project-real-time-coin-info"],
    react_query: ["project-real-time-coin-info"],
    react_apexcharts: ["project-real-time-coin-info"],
    next_intl: ["nextjs-intl"],
    plaiceholder: ["nextjs-image-blur"],
    gtag: ["nextjs-gtag"],
    google_analytics: ["nextjs-gtag"],
    lodash: ["lodash"],
    husky: ["husky-precommit-unauthorized", "husky-git-hook", "husky-commlint"],
    git: [
      "husky-git-hook",
      "husky-commlint",
      "github-repo-union",
      "git-commit-template",
      "error-emeedauth",
    ],
    commitlint: ["husky-commlint"],
    githubpage: ["github-page-publish"],
    intellij: ["git-commit-template"],
    gatsby: ["gatsby-add-table-of-contents-in-gatsby"],
    framer_motion: ["blog-version-2"],
    tailwind: ["blog-version-2"],
    "github_pages_deploy_action@v4": ["blog-auto-deploy"],
    axios: ["axios-interceptor", "axios-config"],
    vanilla_extract: ["assignInlineVars-to-client-from-server"],
  },
};
export default TagsTable;
