// NOTE This file is auto-generated by Contentlayer

import series__blogMdx from './series__blog.mdx.json' with { type: 'json' }
import series__code_snippetsMdx from './series__code_snippets.mdx.json' with { type: 'json' }
import series__commitMsgManagementMdx from './series__commit-msg-management.mdx.json' with { type: 'json' }
import series__network_noteMdx from './series__network_note.mdx.json' with { type: 'json' }
import series__toy_projectMdx from './series__toy_project.mdx.json' with { type: 'json' }
import series__trouble_shootingMdx from './series__trouble_shooting.mdx.json' with { type: 'json' }

export const allSeries = [series__blogMdx, series__code_snippetsMdx, series__commitMsgManagementMdx, series__network_noteMdx, series__toy_projectMdx, series__trouble_shootingMdx]
